language: ruby
cache:
  bundler: true
  directories:
    - node_modules
gemfile: Gemfile
branches:
  only:
  - release
script:
  - gulp
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release
