collections:
  authors:
    output: true
sass:
    style: compressed
    load_paths:
        - _sass
        - node_modules
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"