collections:
  authors:
    output: true
    
# Social Profiles
twitter_username:  perisperis
github_username:   perisperis

# Exclude the following from the Jekyll build process.
# Note: "vendor" is for Travis CI.
exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          ".settings",
          ".sass-cache",
          "Gruntfile.js",
          "node_modules",
          "package.json"]
          
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-paginate