theme: jekyll-theme-architect

title: Pedro Jose García Fernández
description: I work as a Solution Architect for Worldline Iberia. I create solution strategies to update Legacy Applications to Cloud Computing Architectures.